services:
  web:
    build:
      context: ./docker/web
      args:
        PHP_VERSION: "${PHP_VERSION:-8.5}"
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      DB_HOST: mariadb
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.11
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cakephp_test
      MARIADB_USER: cakephp_test
      MARIADB_PASSWORD: secret
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d:cached
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mariadb-data:
