name: Tests

on:
  push:
    branches:
      - 'truephoto'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  linux-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.5'

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: cakephp_test
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, mbstring, pdo_mysql, zip
          ini-values: |
            assert.exception=1,
            zend.assertions=1,
            error_reporting=-1,
            log_errors_max_len=0,
            display_errors=On
          tools: composer

      - name: locale-gen
        run: |
          sudo locale-gen de_DE;
          sudo locale-gen es_ES;

      - name: Create additional databases
        run: |
          env MYSQL_PWD=root mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE cakephp_test2;';
          env MYSQL_PWD=root mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE cakephp_test3;';

      - name: Make temporary directories writable
        run: chmod -R 777 ./app/tmp

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-version }}-composer-

      - name: Install Composer Packages
        run: composer install --no-ansi --no-interaction --no-progress

      - name: Copy database.php
        run: cp ./.github/workflows/configs/database.php ./app/Config/

      - name: Run Tests
        run: ./vendors/bin/phpunit --stderr --verbose lib/Cake/Test/Case/AllTestsTest.php
